# Generated by Django 4.1.7 on 2024-02-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_arrival_date_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='arrival_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
