# Generated by Django 4.1.7 on 2024-02-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_product_arrival_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brandname',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='colour',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='discription',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='mainprice',
            field=models.IntegerField(default=0),
        ),
    ]
