# Generated by Django 4.1.7 on 2024-02-17 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_product_brandname_product_category_product_colour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mainprice',
            field=models.IntegerField(default=0),
        ),
    ]
