# Generated by Django 4.1.7 on 2024-02-17 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_product_mainprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brandname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='colour',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='discription',
            field=models.CharField(max_length=100),
        ),
    ]
